### ISSUE TITLE
Moduł uczniów

### ISSUE THREAD

**Issue by bandurama** [MartyLocke/3ID12B-P-IP-Szkola#6]
Po dodaniu funkcjonalności klas nie działa dodawanie uczniów. W liście uczniów nie wyświetlają się nowo dodani uczniowie, prawdopodobnie nie mają przypisanej klasy. Poprawić po stronie bazy i po stronie wyświetlania. 

Dodatkowo w panelu edycji dodać możliwość ręcznej zmiany klasy dla danego ucznia. (Bez sprawdzania ograniczeń).

**Comment by quakcin** [comment]
ok, zajme sie tym dzisiaj
