### ISSUE TITLE
Generator Klas

### ISSUE THREAD

**Issue by quakcin** [MartyLocke/3ID12B-P-IP-Szkola#7]
Brakuje przypisania numerów uczniów

**Comment by quakcin** [comment]
Brakuje przypisania nauczycieli uczących w poszczegulnych klasach

**Comment by bandurama** [comment]
Pozostało wyświetlać raport z generacji.

**Comment by quakcin** [comment]
> Brakuje przypisania nauczycieli uczących w poszczegulnych klasach

Jednak nie potrzebne - > będzie zrobione w generatorze planu lekcji
