### ISSUE TITLE
Struktura i Styl Kodu

### ISSUE THREAD

**Issue by quakcin** [MartyLocke/3ID12B-P-IP-Szkola#8]
Poprawić styl na bardziej Java'owy
Przenieść mapper do osobnych klas, a logikę do jeszcze innych
Zmienić jdbcTemplate z formattera stringów na obiekotwe podawanie argumentow

**Comment by bandurama** [comment]
Pozostało do zrobienia: moduł nauczycieli oraz moduł klas.

**Comment by bandurama** [comment]
Moduł nauczycieli został zrobiony. Pozostał moduł klas.

**Comment by quakcin** [comment]
Moduł klas gotowy, pozostało zrobić względne oględziny i można zamykać

**Comment by quakcin** [comment]
Chyba cały refaktor zrobiony, panele są na tyle złożone i oddalone od istoty projektu że nie ma sensu ich refaktorować (front-end a nie back-end)
